# Generated by Django 4.2.16 on 2024-12-14 19:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtopics',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'warm-up'), (1, 'choosing the right gym'), (2, 'fitness goals'), (3, 'tips and tricks'), (4, 'consistency'), (5, 'injuries'), (6, 'recovery meals'), (7, 'meal prep'), (8, 'supplements'), (9, 'fat loss'), (10, 'hydration'), (11, 'macros'), (12, 'calories'), (13, 'basics'), (14, 'proper posture'), (15, 'breathing techniques'), (16, 'common mistakes'), (17, 'safety'), (18, 'mobility'), (19, 'full body'), (20, 'push-pull-legs'), (21, 'progressive overload'), (22, 'cardio'), (23, 'strength'), (24, 'HIIT'), (25, 'planning'), (26, 'upper/lower')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.IntegerField(blank=True, choices=[(0, 'advice'), (1, 'diet'), (2, 'form'), (3, 'training schedules'), (4, ' ')], default=4),
        ),
    ]
