# Generated by Django 4.2.16 on 2024-12-17 15:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_goal_post_workout_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='equipment_available',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'none'), (1, 'dumbbells'), (2, 'barbell'), (3, 'resistance_bands'), (4, 'machines'), (5, 'kettlebells'), (6, 'bodyweight'), (7, 'yoga_mat'), (8, 'plates'), (9, 'upright_bike'), (10, 'treadmill')], max_length=22),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_focus',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('weight_loss', 'Weight Loss'), ('muscle_building', 'Muscle Building'), ('balanced', 'Balanced Diet')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('general_fitness', 'General Fitness'), ('flexibility', 'Flexibility'), ('mobility', 'Mobility')], default='general_fitness', max_length=50),
        ),
    ]
